import { PrismaClient } from '@prisma/client';

const DEMO_IMAGE_PREFIX = 'https://dummyimage.com/';
// Stay comfortably under Postgres's ~32767 bind-variable limit per prepared statement.
const CHUNK_SIZE = 10_000;

export interface PurgeDemoStats {
  canonicalProducts: number;
  sourceListings: number;
  priceHistory: number;
  matchDecisions: number;
  reviewQueue: number;
  reviewDecisions: number;
  priceAlerts: number;
  watchlistItems: number;
  seedRuns: number;
  seedCheckpoints: number;
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size));
  }
  return out;
}

/**
 * Deletes marketplace data generated by the synthetic seed pipeline (seed/seed.ts),
 * identified by the dummyimage.com placeholder images that factory always assigns
 * (see seed/factories/canonicalProductFactory.ts and listingFactory.ts). Real listings
 * ingested via LiveIngestionService always carry a real retailer image URL, so this
 * fingerprint never matches them. Runs as plain sequential deletes (not one big
 * transaction) since the full dataset can run into the millions of rows and the
 * script is safely re-runnable if interrupted.
 */
export async function purgeDemoProducts(prisma: PrismaClient): Promise<PurgeDemoStats> {
  const demoProducts = await prisma.canonicalProduct.findMany({
    where: { imageUrl: { startsWith: DEMO_IMAGE_PREFIX } },
    select: { id: true },
  });
  const demoProductIds = demoProducts.map((p) => p.id);
  const productChunks = chunk(demoProductIds, CHUNK_SIZE);

  // Every seed-generated listing (matched or unmatched "challenge" listing) carries
  // the same placeholder image as its source product, so this alone covers all of them.
  const demoListings = await prisma.sourceListing.findMany({
    where: { rawImageUrl: { startsWith: DEMO_IMAGE_PREFIX } },
    select: { id: true },
  });
  const demoListingIds = demoListings.map((l) => l.id);
  const listingChunks = chunk(demoListingIds, CHUNK_SIZE);

  const demoQueueIds: string[] = [];
  for (const ids of listingChunks) {
    const rows = await prisma.reviewQueue.findMany({
      where: { sourceListingId: { in: ids } },
      select: { id: true },
    });
    demoQueueIds.push(...rows.map((r) => r.id));
  }
  const queueChunks = chunk(demoQueueIds, CHUNK_SIZE);

  const stats: PurgeDemoStats = {
    canonicalProducts: 0,
    sourceListings: 0,
    priceHistory: 0,
    matchDecisions: 0,
    reviewQueue: 0,
    reviewDecisions: 0,
    priceAlerts: 0,
    watchlistItems: 0,
    seedRuns: 0,
    seedCheckpoints: 0,
  };

  for (const ids of queueChunks) {
    const result = await prisma.reviewDecision.deleteMany({ where: { queueItemId: { in: ids } } });
    stats.reviewDecisions += result.count;
  }
  for (const ids of queueChunks) {
    const result = await prisma.reviewQueue.deleteMany({ where: { id: { in: ids } } });
    stats.reviewQueue += result.count;
  }
  for (const ids of listingChunks) {
    const result = await prisma.matchDecision.deleteMany({ where: { sourceListingId: { in: ids } } });
    stats.matchDecisions += result.count;
  }
  for (const ids of listingChunks) {
    const result = await prisma.priceHistory.deleteMany({ where: { sourceListingId: { in: ids } } });
    stats.priceHistory += result.count;
  }
  for (const ids of productChunks) {
    const result = await prisma.priceHistory.deleteMany({ where: { canonicalProductId: { in: ids } } });
    stats.priceHistory += result.count;
  }
  for (const ids of productChunks) {
    const result = await prisma.priceAlert.deleteMany({ where: { canonicalProductId: { in: ids } } });
    stats.priceAlerts += result.count;
  }
  for (const ids of productChunks) {
    const result = await prisma.watchlistItem.deleteMany({ where: { canonicalProductId: { in: ids } } });
    stats.watchlistItems += result.count;
  }
  for (const ids of listingChunks) {
    const result = await prisma.sourceListing.deleteMany({ where: { id: { in: ids } } });
    stats.sourceListings += result.count;
  }
  for (const ids of productChunks) {
    const result = await prisma.canonicalProduct.deleteMany({ where: { id: { in: ids } } });
    stats.canonicalProducts += result.count;
  }

  const seedRuns = await prisma.seedRun.deleteMany();
  const seedCheckpoints = await prisma.seedCheckpoint.deleteMany();
  stats.seedRuns = seedRuns.count;
  stats.seedCheckpoints = seedCheckpoints.count;

  return stats;
}

if (require.main === module) {
  const prisma = new PrismaClient();
  purgeDemoProducts(prisma)
    .then((stats) => {
      console.log('[purge-demo-products] Removed:', stats);
    })
    .catch((error) => {
      console.error('[purge-demo-products] Failed:', error);
      process.exitCode = 1;
    })
    .finally(() => prisma.$disconnect());
}
